image: atlassian/default-image:3

pipelines:
  branches:
    dev:
      - step:
          name: 'Deployment to Staging'
          deployment: staging
          script:
            - pipe: atlassian/ssh-run:0.2.6
              variables:
                SSH_USER: 'ubuntu'
                SERVER: '13.50.128.44'
                COMMAND: './devCdScript.sh'
                SSH_KEY: '$SSH_PRIVATE_KEY'

    master:
      - step:
          name: 'Deployment to Production'
          deployment: production
          script:
            - pipe: atlassian/ssh-run:0.2.6
              variables:
                SSH_USER: 'ubuntu'
                SERVER: '13.50.219.88'
                COMMAND: './prodCdScript.sh'
                SSH_KEY: '$SSH_PRIVATE_KEY'