const CountriesList = {
  countries: [
    { country_name: "Albania", region: "Europe" },
    { country_name: "Andorra", region: "Europe" },
    { country_name: "Austria", region: "Europe" },
    { country_name: "Belarus", region: "Europe" },
    { country_name: "Belgium", region: "Europe" },
    { country_name: "Bosnia and Herzegovina", region: "Europe" },
    { country_name: "Bulgaria", region: "Europe" },
    { country_name: "Croatia", region: "Europe" },
    { country_name: "Cyprus", region: "Europe" },
    { country_name: "Czech Republic", region: "Europe" },
    { country_name: "Denmark", region: "Europe" },
    { country_name: "Estonia", region: "Europe" },
    { country_name: "Finland", region: "Europe" },
    { country_name: "France", region: "Europe" },
    { country_name: "Germany", region: "Europe" },
    { country_name: "Greece", region: "Europe" },
    { country_name: "Hungary", region: "Europe" },
    { country_name: "Iceland", region: "Europe" },
    { country_name: "Ireland", region: "Europe" },
    { country_name: "Italy", region: "Europe" },
    { country_name: "Kosovo", region: "Europe" },
    { country_name: "Latvia", region: "Europe" },
    { country_name: "Liechtenstein", region: "Europe" },
    { country_name: "Lithuania", region: "Europe" },
    { country_name: "Luxembourg", region: "Europe" },
    { country_name: "Malta", region: "Europe" },
    { country_name: "Moldova", region: "Europe" },
    { country_name: "Monaco", region: "Europe" },
    { country_name: "Montenegro", region: "Europe" },
    { country_name: "Netherlands", region: "Europe" },
    { country_name: "North Macedonia", region: "Europe" },
    { country_name: "Norway", region: "Europe" },
    { country_name: "Poland", region: "Europe" },
    { country_name: "Portugal", region: "Europe" },
    { country_name: "Romania", region: "Europe" },
    { country_name: "Russia", region: "Europe" },
    { country_name: "San Marino", region: "Europe" },
    { country_name: "Serbia", region: "Europe" },
    { country_name: "Slovakia", region: "Europe" },
    { country_name: "Slovenia", region: "Europe" },
    { country_name: "Spain", region: "Europe" },
    { country_name: "Sweden", region: "Europe" },
    { country_name: "Switzerland", region: "Europe" },
    { country_name: "Turkey", region: "Europe" },
    { country_name: "Ukraine", region: "Europe" },
    { country_name: "United Kingdom", region: "Europe" },
    { country_name: "Vatican City", region: "Europe" },
    { country_name: "Antigua and Barbuda", region: "North America" },
    { country_name: "Bahamas", region: "North America" },
    { country_name: "Barbados", region: "North America" },
    { country_name: "Belize", region: "North America" },
    { country_name: "Canada", region: "North America" },
    { country_name: "Costa Rica", region: "North America" },
    { country_name: "Cuba", region: "North America" },
    { country_name: "Dominica", region: "North America" },
    { country_name: "Dominican Republic", region: "North America" },
    { country_name: "El Salvador", region: "North America" },
    { country_name: "Grenada", region: "North America" },
    { country_name: "Guatemala", region: "North America" },
    { country_name: "Haiti", region: "North America" },
    { country_name: "Honduras", region: "North America" },
    { country_name: "Jamaica", region: "North America" },
    { country_name: "Mexico", region: "North America" },
    { country_name: "Nicaragua", region: "North America" },
    { country_name: "Panama", region: "North America" },
    { country_name: "Saint Kitts and Nevis", region: "North America" },
    { country_name: "Saint Lucia", region: "North America" },
    {
      country_name: "Saint Vincent and the Grenadines",
      region: "North America",
    },
    { country_name: "Trinidad and Tobago", region: "North America" },
    { country_name: "United States", region: "North America" },
    { country_name: "Antarctica", region: "Antarctica" },
    { country_name: "Bahrain", region: "Middle East" },
    { country_name: "Cyprus", region: "Middle East" },
    { country_name: "Egypt", region: "Middle East" },
    { country_name: "Iran", region: "Middle East" },
    { country_name: "Iraq", region: "Middle East" },
    { country_name: "Israel", region: "Middle East" },
    { country_name: "Jordan", region: "Middle East" },
    { country_name: "Kuwait", region: "Middle East" },
    { country_name: "Lebanon", region: "Middle East" },
    { country_name: "Oman", region: "Middle East" },
    { country_name: "Palestine", region: "Middle East" },
    { country_name: "Qatar", region: "Middle East" },
    { country_name: "Saudi Arabia", region: "Middle East" },
    { country_name: "Syria", region: "Middle East" },
    { country_name: "Turkey", region: "Middle East" },
    { country_name: "United Arab Emirates", region: "Middle East" },
    { country_name: "Yemen", region: "Middle East" },
    { country_name: "Algeria", region: "Africa" },
    { country_name: "Angola", region: "Africa" },
    { country_name: "Benin", region: "Africa" },
    { country_name: "Botswana", region: "Africa" },
    { country_name: "Burkina Faso", region: "Africa" },
    { country_name: "Burundi", region: "Africa" },
    { country_name: "Cabo Verde", region: "Africa" },
    { country_name: "Cameroon", region: "Africa" },
    { country_name: "Central African Republic", region: "Africa" },
    { country_name: "Chad", region: "Africa" },
    { country_name: "Comoros", region: "Africa" },
    { country_name: "Democratic Republic of the Congo", region: "Africa" },
    { country_name: "Djibouti", region: "Africa" },
    { country_name: "Egypt", region: "Africa" },
    { country_name: "Equatorial Guinea", region: "Africa" },
    { country_name: "Eritrea", region: "Africa" },
    { country_name: "Eswatini", region: "Africa" },
    { country_name: "Ethiopia", region: "Africa" },
    { country_name: "Gabon", region: "Africa" },
    { country_name: "Gambia", region: "Africa" },
    { country_name: "Ghana", region: "Africa" },
    { country_name: "Guinea", region: "Africa" },
    { country_name: "Guinea-Bissau", region: "Africa" },
    { country_name: "Ivory Coast", region: "Africa" },
    { country_name: "Kenya", region: "Africa" },
    { country_name: "Lesotho", region: "Africa" },
    { country_name: "Liberia", region: "Africa" },
    { country_name: "Libya", region: "Africa" },
    { country_name: "Madagascar", region: "Africa" },
    { country_name: "Malawi", region: "Africa" },
    { country_name: "Mali", region: "Africa" },
    { country_name: "Mauritania", region: "Africa" },
    { country_name: "Mauritius", region: "Africa" },
    { country_name: "Morocco", region: "Africa" },
    { country_name: "Mozambique", region: "Africa" },
    { country_name: "Namibia", region: "Africa" },
    { country_name: "Niger", region: "Africa" },
    { country_name: "Nigeria", region: "Africa" },
    { country_name: "Republic of the Congo", region: "Africa" },
    { country_name: "Rwanda", region: "Africa" },
    { country_name: "Sao Tome and Principe", region: "Africa" },
    { country_name: "Senegal", region: "Africa" },
    { country_name: "Seychelles", region: "Africa" },
    { country_name: "Sierra Leone", region: "Africa" },
    { country_name: "Somalia", region: "Africa" },
    { country_name: "South Africa", region: "Africa" },
    { country_name: "South Sudan", region: "Africa" },
    { country_name: "Sudan", region: "Africa" },
    { country_name: "Tanzania", region: "Africa" },
    { country_name: "Togo", region: "Africa" },
    { country_name: "Tunisia", region: "Africa" },
    { country_name: "Uganda", region: "Africa" },
    { country_name: "Zambia", region: "Africa" },
    { country_name: "Zimbabwe", region: "Africa" },
    { country_name: "Antarctica", region: "Antarctica" },
    { country_name: "Afghanistan", region: "Asia" },
    { country_name: "Armenia", region: "Asia" },
    { country_name: "Azerbaijan", region: "Asia" },
    { country_name: "Bahrain", region: "Asia" },
    { country_name: "Bangladesh", region: "Asia" },
    { country_name: "Bhutan", region: "Asia" },
    { country_name: "Brunei", region: "Asia" },
    { country_name: "Cambodia", region: "Asia" },
    { country_name: "China", region: "Asia" },
    { country_name: "Cyprus", region: "Asia" },
    { country_name: "Georgia", region: "Asia" },
    { country_name: "India", region: "Asia" },
    { country_name: "Indonesia", region: "Asia" },
    { country_name: "Iran", region: "Asia" },
    { country_name: "Iraq", region: "Asia" },
    { country_name: "Israel", region: "Asia" },
    { country_name: "Japan", region: "Asia" },
    { country_name: "Jordan", region: "Asia" },
    { country_name: "Kazakhstan", region: "Asia" },
    { country_name: "Kuwait", region: "Asia" },
    { country_name: "Kyrgyzstan", region: "Asia" },
    { country_name: "Laos", region: "Asia" },
    { country_name: "Lebanon", region: "Asia" },
    { country_name: "Malaysia", region: "Asia" },
    { country_name: "Maldives", region: "Asia" },
    { country_name: "Mongolia", region: "Asia" },
    { country_name: "Myanmar", region: "Asia" },
    { country_name: "Nepal", region: "Asia" },
    { country_name: "North Korea", region: "Asia" },
    { country_name: "Oman", region: "Asia" },
    { country_name: "Pakistan", region: "Asia" },
    { country_name: "Palestine", region: "Asia" },
    { country_name: "Philippines", region: "Asia" },
    { country_name: "Qatar", region: "Asia" },
    { country_name: "Saudi Arabia", region: "Asia" },
    { country_name: "Singapore", region: "Asia" },
    { country_name: "South Korea", region: "Asia" },
    { country_name: "Sri Lanka", region: "Asia" },
    { country_name: "Syria", region: "Asia" },
    { country_name: "Taiwan", region: "Asia" },
    { country_name: "Tajikistan", region: "Asia" },
    { country_name: "Thailand", region: "Asia" },
    { country_name: "Timor-Leste", region: "Asia" },
    { country_name: "Turkey", region: "Asia" },
    { country_name: "Turkmenistan", region: "Asia" },
    { country_name: "United Arab Emirates", region: "Asia" },
    { country_name: "Uzbekistan", region: "Asia" },
    { country_name: "Vietnam", region: "Asia" },
    { country_name: "Yemen", region: "Asia" },
    { country_name: "Australia", region: "Oceania" },
    { country_name: "Fiji", region: "Oceania" },
    { country_name: "Kiribati", region: "Oceania" },
    { country_name: "Marshall Islands", region: "Oceania" },
    { country_name: "Micronesia", region: "Oceania" },
    { country_name: "Nauru", region: "Oceania" },
    { country_name: "New Zealand", region: "Oceania" },
    { country_name: "Palau", region: "Oceania" },
    { country_name: "Papua New Guinea", region: "Oceania" },
    { country_name: "Samoa", region: "Oceania" },
    { country_name: "Solomon Islands", region: "Oceania" },
    { country_name: "Tonga", region: "Oceania" },
    { country_name: "Tuvalu", region: "Oceania" },
    { country_name: "Vanuatu", region: "Oceania" },
    { country_name: "Argentina", region: "LATAM" },
    { country_name: "Bolivia", region: "LATAM" },
    { country_name: "Brazil", region: "LATAM" },
    { country_name: "Chile", region: "LATAM" },
    { country_name: "Colombia", region: "LATAM" },
    { country_name: "Costa Rica", region: "LATAM" },
    { country_name: "Cuba", region: "LATAM" },
    { country_name: "Dominican Republic", region: "LATAM" },
    { country_name: "Ecuador", region: "LATAM" },
    { country_name: "El Salvador", region: "LATAM" },
    { country_name: "Guatemala", region: "LATAM" },
    { country_name: "Haiti", region: "LATAM" },
    { country_name: "Honduras", region: "LATAM" },
    { country_name: "Jamaica", region: "LATAM" },
    { country_name: "Mexico", region: "LATAM" },
    { country_name: "Nicaragua", region: "LATAM" },
    { country_name: "Panama", region: "LATAM" },
    { country_name: "Paraguay", region: "LATAM" },
    { country_name: "Peru", region: "LATAM" },
    { country_name: "Puerto Rico", region: "LATAM" },
    { country_name: "Suriname", region: "LATAM" },
    { country_name: "Trinidad and Tobago", region: "LATAM" },
    { country_name: "Uruguay", region: "LATAM" },
    { country_name: "Venezuela", region: "LATAM" },
  ],
};

module.exports = {
  CountriesList,
};
